### PR TITLE
Feature news week home page

### PR DESCRIPTION
**Pull request by yaairfernando**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
### Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Good job Fernando🙂,
Your project is awesome 
Let us take care of these two issues to have our project approved
* [ ] Let us fix Html validator results.🙂
* [ ] Let us get rid of all inline styling. Check lines 104,117,128,139,163,151 and any other place in the code where these occur.🙂
### Kindly make these changes and submit the project for review🙂.
feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
### Happy coding🙂

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi Yairi!  
#### Your project looks :+1:  and very discriptive readme file!
#### But need some Required Changes


### Page structure

#### Navigation bar

* [x] It contains Newsweek logo
* [x] It contains current date
* [x] It contains Sign in and Subscribe links
* [x] It contains main navigation links
* [ ] **It changes with RWD breakpoints**

#### *** Original [Newsweek](https://www.newsweek.com/) ***
3gw68t

#### *** On your version of Newsweek navbar not responsive yet***
3gw6m5


#### Main content
- [x] You have all necessary parts but one little error please make "Features Stories" and "Opinion" - uppercase. They should be "FEATURED STORIES" and "OPINION".



- [ ] **It changes with RWD breakpoints**

#### *** Original ***


#### *** Yor version  ***


#### *** Original ***

#### *** Yor version  ***


#### *** Original ***



#### *** Yor version  ***


#### *** Original ***


#### *** Yor version  ***


#### *** Original ***


#### *** Yor version  ***


#### Footer

* [x] It contains Newsweek logo 
* [x] It contains social media icons
* [x] It contains main navigation links
* [x] **It changes with RWD breakpoints** 

#### Implementation details

* [x] It references Bootstrap CSS file](https://getbootstrap.com/docs/4.3/getting-started/introduction/#css) 
* [x] It adds [viewport metatag](https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag) 
* [ ] It uses Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)). You have very big file style.css, kindly recommended use Bootstrap classes.





- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. 

*** It steel shows ERROR From line 13, column 3; to line 13, column 109 ***
validator

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes.

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello @YairFernando67 , 👋 

-  Should have a top sticky navbar when we scroll down. because original site has a sticky navbar.
-  [Optional] Still not fixed the HTML validation error. This is optional only because error was from google font cdn. Even though try to fix it ⚙️. 


----
### Make changes and submit another code review request.
----
#### Happy coding
**Pon Muthu Selvam N**
_If you have any questions, let me know on slack (Pon Muthu Selvam) and I will be glad to clarify with you_

**Review by imhta — APPROVED** [review]
# Project Approved :star: 

### Hello @YairFernando67 , 👋  
You have done a great job in this project :+1: 

----
## Don't Forgot to submit project completion form
----
#### Happy coding
**Pon Muthu Selvam N**

**Pull request merged**
